// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.github-project-sync@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const GITHUB_PROJECT_SYNC_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const GITHUB_PROJECT_SYNC_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_github_project_sync { () => { "{\"capability_id\":\"lenso.github-project-sync@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"get_binding\",\"ingest_webhook\",\"list_bindings\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_github_project_sync_client { () => { "{\"capability_id\":\"lenso.github-project-sync@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_github_project_sync_client { () => { "{\"capability_id\":\"lenso.github-project-sync@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const GET_BINDING_OPERATION: &str = "get_binding";
pub const INGEST_WEBHOOK_OPERATION: &str = "ingest_webhook";
pub const LIST_BINDINGS_OPERATION: &str = "list_bindings";

pub use lenso_contract_runtime::{Bytes, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetBindingRequest {
    #[serde(rename = "github_issue_number")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub github_issue_number: i64,
    #[serde(rename = "mapping_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mapping_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetBindingResponse {
    #[serde(rename = "github_issue_number")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub github_issue_number: i64,
    #[serde(rename = "github_node_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub github_node_id: String,
    #[serde(rename = "github_project_item_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub github_project_item_id: Option<String>,
    #[serde(rename = "github_repository_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub github_repository_id: String,
    #[serde(rename = "lenso_issue_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lenso_issue_id: String,
    #[serde(rename = "mapping_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mapping_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetBindingError {
    DeliveryConflict,
    DependencyFailure,
    Forbidden,
    InvalidRequest,
    InvalidSignature,
    MappingInactive,
    NotFound,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IngestWebhookRequest {
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: Bytes,
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "event")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event: String,
    #[serde(rename = "signature_256")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub signature_256: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IngestWebhookResponse {
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "duplicate")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub duplicate: bool,
    #[serde(rename = "received_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub received_at: Timestamp,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: IngestWebhookResponseState,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum IngestWebhookResponseState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "retry")]
    Retry,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "dead")]
    Dead,
}

#[derive(Clone, Debug, PartialEq)]
pub enum IngestWebhookError {
    DeliveryConflict,
    DependencyFailure,
    Forbidden,
    InvalidRequest,
    InvalidSignature,
    MappingInactive,
    NotFound,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListBindingsRequest {
    #[serde(rename = "after")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub after: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "mapping_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mapping_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListBindingsResponse {
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<ListBindingsResponseItemsItem>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListBindingsResponseItemsItem {
    #[serde(rename = "github_issue_number")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub github_issue_number: i64,
    #[serde(rename = "github_node_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub github_node_id: String,
    #[serde(rename = "github_project_item_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub github_project_item_id: Option<String>,
    #[serde(rename = "github_repository_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub github_repository_id: String,
    #[serde(rename = "lenso_issue_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lenso_issue_id: String,
    #[serde(rename = "mapping_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mapping_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListBindingsError {
    DeliveryConflict,
    DependencyFailure,
    Forbidden,
    InvalidRequest,
    InvalidSignature,
    MappingInactive,
    NotFound,
    RevisionConflict,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct GithubProjectSyncGetBinding;
impl RequestCapability for GithubProjectSyncGetBinding {
    type Request = GetBindingRequest;
    type Response = GetBindingResponse;
    type DomainError = GetBindingError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_BINDING_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<GithubProjectSyncRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_binding(context, request)
    }
}

#[derive(Debug)]
pub struct GithubProjectSyncIngestWebhook;
impl RequestCapability for GithubProjectSyncIngestWebhook {
    type Request = IngestWebhookRequest;
    type Response = IngestWebhookResponse;
    type DomainError = IngestWebhookError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INGEST_WEBHOOK_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<GithubProjectSyncRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).ingest_webhook(context, request)
    }
}

#[derive(Debug)]
pub struct GithubProjectSyncListBindings;
impl RequestCapability for GithubProjectSyncListBindings {
    type Request = ListBindingsRequest;
    type Response = ListBindingsResponse;
    type DomainError = ListBindingsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_BINDINGS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<GithubProjectSyncRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_bindings(context, request)
    }
}

impl serde::Serialize for GetBindingError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DeliveryConflict => serializer.serialize_str("delivery_conflict"),
            Self::DependencyFailure => serializer.serialize_str("dependency_failure"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidSignature => serializer.serialize_str("invalid_signature"),
            Self::MappingInactive => serializer.serialize_str("mapping_inactive"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetBindingError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "delivery_conflict" => Ok(Self::DeliveryConflict),
                "dependency_failure" => Ok(Self::DependencyFailure),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_signature" => Ok(Self::InvalidSignature),
                "mapping_inactive" => Ok(Self::MappingInactive),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for IngestWebhookError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DeliveryConflict => serializer.serialize_str("delivery_conflict"),
            Self::DependencyFailure => serializer.serialize_str("dependency_failure"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidSignature => serializer.serialize_str("invalid_signature"),
            Self::MappingInactive => serializer.serialize_str("mapping_inactive"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for IngestWebhookError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "delivery_conflict" => Ok(Self::DeliveryConflict),
                "dependency_failure" => Ok(Self::DependencyFailure),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_signature" => Ok(Self::InvalidSignature),
                "mapping_inactive" => Ok(Self::MappingInactive),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListBindingsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DeliveryConflict => serializer.serialize_str("delivery_conflict"),
            Self::DependencyFailure => serializer.serialize_str("dependency_failure"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidSignature => serializer.serialize_str("invalid_signature"),
            Self::MappingInactive => serializer.serialize_str("mapping_inactive"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListBindingsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "delivery_conflict" => Ok(Self::DeliveryConflict),
                "dependency_failure" => Ok(Self::DependencyFailure),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_signature" => Ok(Self::InvalidSignature),
                "mapping_inactive" => Ok(Self::MappingInactive),
                "not_found" => Ok(Self::NotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_get_binding_request(value: &GetBindingRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_binding_request(wire: &str) -> Result<GetBindingRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_binding_response(value: &GetBindingResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_binding_response(wire: &str) -> Result<GetBindingResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_binding_error(value: &GetBindingError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_binding_error(wire: &str) -> Result<GetBindingError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_ingest_webhook_request(value: &IngestWebhookRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ingest_webhook_request(wire: &str) -> Result<IngestWebhookRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_ingest_webhook_response(value: &IngestWebhookResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ingest_webhook_response(wire: &str) -> Result<IngestWebhookResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_ingest_webhook_error(value: &IngestWebhookError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ingest_webhook_error(wire: &str) -> Result<IngestWebhookError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_bindings_request(value: &ListBindingsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_bindings_request(wire: &str) -> Result<ListBindingsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_bindings_response(value: &ListBindingsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_bindings_response(wire: &str) -> Result<ListBindingsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_bindings_error(value: &ListBindingsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_bindings_error(wire: &str) -> Result<ListBindingsError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoGithubProjectSyncGetBindingResult {
    fn __lenso_into_result(self) -> Result<Result<GetBindingResponse, GetBindingError>, RuntimeFailure>;
}
impl __LensoIntoGithubProjectSyncGetBindingResult for Result<GetBindingResponse, GetBindingError> {
    fn __lenso_into_result(self) -> Result<Result<GetBindingResponse, GetBindingError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoGithubProjectSyncGetBindingResult for Result<Result<GetBindingResponse, GetBindingError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetBindingResponse, GetBindingError>, RuntimeFailure> { self }
}
impl __LensoIntoGithubProjectSyncGetBindingResult for Result<GetBindingResponse, lenso_plugin_authoring::PluginError<GetBindingError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetBindingResponse, GetBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoGithubProjectSyncGetBindingResult for Result<GetBindingResponse, GithubProjectSyncGetBindingInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetBindingResponse, GetBindingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(GithubProjectSyncGetBindingInvocationError::Domain(error)) => Ok(Err(error)),
            Err(GithubProjectSyncGetBindingInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoGithubProjectSyncIngestWebhookResult {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure>;
}
impl __LensoIntoGithubProjectSyncIngestWebhookResult for Result<IngestWebhookResponse, IngestWebhookError> {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoGithubProjectSyncIngestWebhookResult for Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> { self }
}
impl __LensoIntoGithubProjectSyncIngestWebhookResult for Result<IngestWebhookResponse, lenso_plugin_authoring::PluginError<IngestWebhookError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoGithubProjectSyncIngestWebhookResult for Result<IngestWebhookResponse, GithubProjectSyncIngestWebhookInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(GithubProjectSyncIngestWebhookInvocationError::Domain(error)) => Ok(Err(error)),
            Err(GithubProjectSyncIngestWebhookInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoGithubProjectSyncListBindingsResult {
    fn __lenso_into_result(self) -> Result<Result<ListBindingsResponse, ListBindingsError>, RuntimeFailure>;
}
impl __LensoIntoGithubProjectSyncListBindingsResult for Result<ListBindingsResponse, ListBindingsError> {
    fn __lenso_into_result(self) -> Result<Result<ListBindingsResponse, ListBindingsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoGithubProjectSyncListBindingsResult for Result<Result<ListBindingsResponse, ListBindingsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListBindingsResponse, ListBindingsError>, RuntimeFailure> { self }
}
impl __LensoIntoGithubProjectSyncListBindingsResult for Result<ListBindingsResponse, lenso_plugin_authoring::PluginError<ListBindingsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListBindingsResponse, ListBindingsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoGithubProjectSyncListBindingsResult for Result<ListBindingsResponse, GithubProjectSyncListBindingsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListBindingsResponse, ListBindingsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(GithubProjectSyncListBindingsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(GithubProjectSyncListBindingsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait GithubProjectSyncProvider: fmt::Debug + 'static {
    fn get_binding(&self, context: InvocationContext, request: GetBindingRequest) -> NativeRequestFuture<GithubProjectSyncGetBinding>;
    fn ingest_webhook(&self, context: InvocationContext, request: IngestWebhookRequest) -> NativeRequestFuture<GithubProjectSyncIngestWebhook>;
    fn list_bindings(&self, context: InvocationContext, request: ListBindingsRequest) -> NativeRequestFuture<GithubProjectSyncListBindings>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_github_project_sync {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportGithubProjectSync;
        impl $crate::GithubProjectSyncProvider for $plugin {
        fn get_binding(&self, context: __LensoNativeSupportGithubProjectSync::InvocationContext, request: $crate::GetBindingRequest) -> __LensoNativeSupportGithubProjectSync::NativeRequestFuture<$crate::GithubProjectSyncGetBinding> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_binding(&plugin, context, request).await;
                $crate::__LensoIntoGithubProjectSyncGetBindingResult::__lenso_into_result(result)
            })
        }
        fn ingest_webhook(&self, context: __LensoNativeSupportGithubProjectSync::InvocationContext, request: $crate::IngestWebhookRequest) -> __LensoNativeSupportGithubProjectSync::NativeRequestFuture<$crate::GithubProjectSyncIngestWebhook> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::ingest_webhook(&plugin, context, request).await;
                $crate::__LensoIntoGithubProjectSyncIngestWebhookResult::__lenso_into_result(result)
            })
        }
        fn list_bindings(&self, context: __LensoNativeSupportGithubProjectSync::InvocationContext, request: $crate::ListBindingsRequest) -> __LensoNativeSupportGithubProjectSync::NativeRequestFuture<$crate::GithubProjectSyncListBindings> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_bindings(&plugin, context, request).await;
                $crate::__LensoIntoGithubProjectSyncListBindingsResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct GithubProjectSyncRequestEndpoint { provider: Rc<dyn GithubProjectSyncProvider> }

#[derive(Debug)]
pub struct GithubProjectSyncEndpoint<P: GithubProjectSyncProvider> { provider: Rc<P>, request_endpoint: GithubProjectSyncRequestEndpoint }
impl<P: GithubProjectSyncProvider> GithubProjectSyncEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn GithubProjectSyncProvider> = provider.clone();
        Self { provider, request_endpoint: GithubProjectSyncRequestEndpoint { provider: request_provider } }
    }
}

impl<P: GithubProjectSyncProvider> NativeRequestEndpoint for GithubProjectSyncEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        GET_BINDING_OPERATION,
        INGEST_WEBHOOK_OPERATION,
        LIST_BINDINGS_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            GET_BINDING_OPERATION => {
                let Ok(request) = request.downcast::<GetBindingRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_binding(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            INGEST_WEBHOOK_OPERATION => {
                let Ok(request) = request.downcast::<IngestWebhookRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).ingest_webhook(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_BINDINGS_OPERATION => {
                let Ok(request) = request.downcast::<ListBindingsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_bindings(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_github_project_sync {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::GithubProjectSyncEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_github_project_sync {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_github_project_sync!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct GithubProjectSyncClient {
    get_binding: NativeRequestHandle<GithubProjectSyncGetBinding>,
    ingest_webhook: NativeRequestHandle<GithubProjectSyncIngestWebhook>,
    list_bindings: NativeRequestHandle<GithubProjectSyncListBindings>,
}
impl GithubProjectSyncClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn get_binding(&self, request: GetBindingRequest) -> Result<GetBindingResponse, GithubProjectSyncGetBindingInvocationError> {
        self.get_binding.invoke(GET_BINDING_OPERATION, request).await
            .map_err(GithubProjectSyncGetBindingInvocationError::Runtime)?
            .map_err(GithubProjectSyncGetBindingInvocationError::Domain)
    }

    pub async fn get_binding_with_context(&self, context: InvocationContext, request: GetBindingRequest) -> Result<GetBindingResponse, GithubProjectSyncGetBindingInvocationError> {
        self.get_binding.invoke_with_context(GET_BINDING_OPERATION, context, request).await
            .map_err(GithubProjectSyncGetBindingInvocationError::Runtime)?
            .map_err(GithubProjectSyncGetBindingInvocationError::Domain)
    }

    pub async fn ingest_webhook(&self, request: IngestWebhookRequest) -> Result<IngestWebhookResponse, GithubProjectSyncIngestWebhookInvocationError> {
        self.ingest_webhook.invoke(INGEST_WEBHOOK_OPERATION, request).await
            .map_err(GithubProjectSyncIngestWebhookInvocationError::Runtime)?
            .map_err(GithubProjectSyncIngestWebhookInvocationError::Domain)
    }

    pub async fn ingest_webhook_with_context(&self, context: InvocationContext, request: IngestWebhookRequest) -> Result<IngestWebhookResponse, GithubProjectSyncIngestWebhookInvocationError> {
        self.ingest_webhook.invoke_with_context(INGEST_WEBHOOK_OPERATION, context, request).await
            .map_err(GithubProjectSyncIngestWebhookInvocationError::Runtime)?
            .map_err(GithubProjectSyncIngestWebhookInvocationError::Domain)
    }

    pub async fn list_bindings(&self, request: ListBindingsRequest) -> Result<ListBindingsResponse, GithubProjectSyncListBindingsInvocationError> {
        self.list_bindings.invoke(LIST_BINDINGS_OPERATION, request).await
            .map_err(GithubProjectSyncListBindingsInvocationError::Runtime)?
            .map_err(GithubProjectSyncListBindingsInvocationError::Domain)
    }

    pub async fn list_bindings_with_context(&self, context: InvocationContext, request: ListBindingsRequest) -> Result<ListBindingsResponse, GithubProjectSyncListBindingsInvocationError> {
        self.list_bindings.invoke_with_context(LIST_BINDINGS_OPERATION, context, request).await
            .map_err(GithubProjectSyncListBindingsInvocationError::Runtime)?
            .map_err(GithubProjectSyncListBindingsInvocationError::Domain)
    }
}

impl CapabilityClient for GithubProjectSyncClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            get_binding: dependencies.one::<GithubProjectSyncGetBinding>()?,
            ingest_webhook: dependencies.one::<GithubProjectSyncIngestWebhook>()?,
            list_bindings: dependencies.one::<GithubProjectSyncListBindings>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for GithubProjectSyncClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    get_binding: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<GithubProjectSyncGetBinding>()?,
                    ingest_webhook: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<GithubProjectSyncIngestWebhook>()?,
                    list_bindings: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<GithubProjectSyncListBindings>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum GithubProjectSyncGetBindingInvocationError {
    Domain(GetBindingError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum GithubProjectSyncIngestWebhookInvocationError {
    Domain(IngestWebhookError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum GithubProjectSyncListBindingsInvocationError {
    Domain(ListBindingsError),
    Runtime(RuntimeFailure),
}
